name: flutter_mwebd
description: "A Flutter package for https://github.com/Cyrix126/mwebd-wrapper"
version: 0.0.1-pre.12
homepage: https://github.com/cypherstack/flutter_mwebd
issue_tracker: https://github.com/cypherstack/flutter_mwebd/issues

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  hooks: ^2.0.2

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
