// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset(
  'package:flutter_mwebd/src/flutter_mwebd_bindings_generated.dart',
)
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.UintPtr Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external int CreateServer(
  ffi.Pointer<ffi.Char> chain,
  ffi.Pointer<ffi.Char> dataDir,
  ffi.Pointer<ffi.Char> peer,
  ffi.Pointer<ffi.Char> proxy,
);

@ffi.Native<ffi.Int Function(ffi.UintPtr, ffi.Int)>()
external int StartServer(int id, int port);

@ffi.Native<ffi.Void Function(ffi.UintPtr)>()
external void StopServer(int id);

@ffi.Native<ffi.Void Function(ffi.UintPtr, ffi.Pointer<StatusResponse>)>()
external void Status(int id, ffi.Pointer<StatusResponse> out);

final class StatusResponse extends ffi.Struct {
  @ffi.Int32()
  external int block_header_height;

  @ffi.Int32()
  external int mweb_header_height;

  @ffi.Int32()
  external int mweb_utxos_height;

  @ffi.Uint32()
  external int block_time;
}
